name: Lottery
version: 1.0
description: Daegonner's Lottery Plugin
author: SainttX

main: com.daegonner.lottery.Lottery
depend: [Core]

commands:
  lottery:
    description: Lottery commands
    aliases: [lotto, lot]